### PR TITLE
fix:dynamic router is constructed when the notified address is 'route…

### PR DESCRIPTION
**Pull request by venusDo**
fix issue [743](https://github.com/apache/dubbo-go/issues/743)

### CODE REVIEW

**Review by hxmhlt — DISMISSED** [review]
Is this pr can resolve  #734 ?

**Review by beiwei30 — APPROVED** [review]
//lgtm

**Review by AlexStocks — APPROVED** [review]

**Review by zouyx — COMMENTED** [review]
what about this PR ? if not any process , will close in 31th.Dec

**Review by cityiron — APPROVED** [review]

**Review by IronCity — COMMENTED** [review]
pls check CI

**Review by cityiron — COMMENTED** [review]
pls check this pr CI

**Review by LaurenceLiZhixin — APPROVED** [review]

**Pull request closed without merging**
