### PR TITLE
Remove protoc-gen-dubbo & protoc-gen-dubbo3 tool

### PR DESCRIPTION
**Pull request by cjphaha**
* 删除 protocol/dubbo3/protoc-gen-dubbo3 和 protocol/grpc/protoc-gen-dubbo

### CODE REVIEW

**Review by zouyx — COMMENTED** [review]
Is it ready for merge? If not make it draft pls.

**Comment by cjphaha** [comment]
> Is it ready for merge? If not make it draft pls.

ok~

**Comment by cjphaha** [comment]
> Is it ready for merge? If not make it draft pls.

now it is ready for review

**Review by ztelur — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]

**Comment by LaurenceLiZhixin** [comment]
这个pr先放着，暂时不急着合并

**Pull request merged**
