### PR TITLE
update protoc-gen-go-triple

### PR DESCRIPTION
**Pull request by FinalT**
Optimized file generation logic
Keep pb files and triple files in the same directory
Update README

### CODE REVIEW

**Comment by chickenlj** [comment]
What's this for? Please provide more details about this change.

**Review by chickenlj — APPROVED** [review]
LGTM.

**Comment by chickenlj** [comment]
We need to update the `generated files` in apache/dubbo-go-samples after this patch is merged.

**Comment by FinalT** [comment]
> We need to update the `generated files` in apache/dubbo-go-samples after this patch is merged.

I will update the generated files after this patch is merged.

**Pull request merged**
