### PR TITLE
Ftr:issue 222

### PR DESCRIPTION
**Pull request by pantianying**
**What this PR does**:
https://github.com/apache/dubbo-go/issues/222
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by pantianying** [comment]
@fangyincheng pls review

**Comment by hxmhlt** [comment]
I suggest that we should limit the condition  for not retry instead of limiting the condition for retry.
Because I think there should be more cases where retries are needed than where retries are not needed. And it's hard to enumerate them for us.

In dubbo, it limited that only user custom exceptions are not needed to retry. In addition, other exceptions should be caught and retried.

**Comment by hxmhlt** [comment]
Maybe we need a better solution for this issue. @fangyincheng @pantianying

**Comment by pantianying** [comment]
> Maybe we need a better solution for this issue. @fangyincheng @pantianying

I agreed , pls ignore this pr

**Pull request closed without merging**
