### PR TITLE
fix cannot call go provider service when used by java dubbo 2.7.7 version

### PR DESCRIPTION
**Pull request by jack15083**
**What this PR does**:
remove empty provider registry param key 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by zouyx — COMMENTED** [review]
Is it the same to this PR?

https://github.com/apache/dubbo-go/pull/773

**Comment by jack15083** [comment]
> Is it the same to this PR?
> 
> #773

看了一下不一样，这个是优化了一上注册到注册中心的url  注册时去掉值为空的参数。

**Review by AlexStocks — APPROVED** [review]

**Comment by zouyx** [comment]
> > Is it the same to this PR?
> > #773
> 
> 看了一下不一样，这个是优化了一上注册到注册中心的url 注册时去掉值为空的参数。

773 是从 url 里把为空的参数都去掉。

**Review by zouyx — COMMENTED** [review]
Could you help to add a ut for this fix?

**Review by fangyincheng — APPROVED** [review]

**Review by watermelo — APPROVED** [review]

**Pull request merged**
