### PR TITLE
Rft: Metadata service

### PR DESCRIPTION
**Pull request by xavier-niu**
**What this PR does**:

- Rename package names of metadata service both for local and remote.
- Update README.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This PR is opened after talking with @flycash. IMO, name problems should be resolved ASAP in release candidate stages.

**Does this PR introduce a user-facing change?**:

```release-note
Users may encounter some errors when calling `inmemory.MetadataService` or `remote.MetadataService`, dubbo-go should be updated to the latest version to address that problem.
```

### CODE REVIEW

**Comment by flycash** [comment]
I am not sure if this is a good idea because those package has been exposed to users.

**Comment by xavier-niu** [comment]
> I am not sure if this is a good idea because those package has been exposed to users.

In fact, the remote.RemoteMetedataService was renamed in the RC2. I think the package name should be changed ASAP if the name could be determined and be immutable in the future, it could help the people who are new to dubbo-go know the components quickly.

If the compatibility with older systems is one of the important things, I think `inmemory` package could be reserved and marked as deprecated in the comments.

**Comment by flycash** [comment]
I understand your concern. So I say I am not sure if it's a good idea. @AlexStocks @zouyx what do you think?

**Comment by AlexStocks** [comment]
@flycash I think there are not so many people using this package now. It's a good time for us to change the package name.

**Review by AlexStocks — APPROVED** [review]

**Review by flycash — APPROVED** [review]

**Review by hxmhlt — APPROVED** [review]

**Pull request merged**
