### PR TITLE
filter registry url params starting with dot

### PR DESCRIPTION
**Pull request by CodingSinger**
filter registry url params starting with dot.

### CODE REVIEW

**Comment by CodingSinger** [comment]
> Will it cause compatibility issues between new version and old version?
Usually not, unless you use a key that starts with dot in the old version.

**Comment by zouyx** [comment]
> Why do we need to add "."

maybe he has added in `dubbo` ? [doge]

**Comment by CodingSinger** [comment]
> Why do we need to add "."

Maybe we will have some sensitive fields that we don’t want to pass to the consumer side via url. For example, secret or password...

**Comment by shalk** [comment]
This is good way to  hiden ak/ak from  dubbo url.

do this feature merge into java version ?

**Comment by zouyx** [comment]
> This is good way to hiden ak/ak from dubbo url.
> 
> do this feature merge into java version ?

https://github.com/apache/dubbo/pull/5878, do you want this feature? 

if you have a problem ,you can create a new issue rather than reply in closed issue.

**Pull request merged**
