### PR TITLE
Fix: Nacos remoting and config_center

### PR DESCRIPTION
**Pull request by mosandao**
**What this PR does**:
修改 nacos 无法注册指定命名空间
修改 nacos 无法获取指定命名空间配置文件
**Special notes for your reviewer**:
修改了四处代码
common/constant/key.go
config_center/nacos/client.go
remoting/nacos/builder.go
registry/nacos/registry.go

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Review by AlexStocks — APPROVED** [review]

**Review by xianlezheng — APPROVED** [review]

**Comment by zouyx** [comment]
@lzp0412 Could you like to review this PR?

**Review by zouyx — COMMENTED** [review]
Would you like provide which version of nacos have you test

**Comment by mosandao** [comment]
> Would you like provide which version of nacos have you test
NACOS  version 1.3.2

**Comment by lzp0412** [comment]
I don't understand why change to namesapce. I think it's just a config key

**Comment by lzp0412** [comment]
Some older versions user have already used the namespaceId as the key of the configuration. This change will cause incompatibility.

**Comment by zouyx** [comment]
> Some older versions user have already used the namespaceId as the key of the configuration. This change will cause incompatibility.

Could you explain why do you change to namesapce?

**Comment by mosandao** [comment]
> > Some older versions user have already used the namespaceId as the key of the configuration. This change will cause incompatibility.
> 
> Could you explain why do you change to namesapce? @mosandao

因为在加载配置文件的时候，加载进来的key是namesapce，而不是namesapceId，导致无法从指定命名空间读取配置文件

**Comment by lzp0412** [comment]
> > > Some older versions user have already used the namespaceId as the key of the configuration. This change will cause incompatibility.
> > 
> > 
> > Could you explain why do you change to namesapce? @mosandao
> 
> 因为在加载配置文件的时候，加载进来的key是namesapce，而不是namesapceId，导致无法从指定命名空间读取配置文件

这个key在配置文件里面可以自己修改的。 @mosandao

**Comment by mosandao** [comment]
> > > > Some older versions user have already used the namespaceId as the key of the configuration. This change will cause incompatibility.
> > > 
> > > 
> > > Could you explain why do you change to namesapce? @mosandao
> > 
> > 
> > 因为在加载配置文件的时候，加载进来的key是namesapce，而不是namesapceId，导致无法从指定命名空间读取配置文件
> 
> 这个key在配置文件里面可以自己修改的。 @mosandao

在config_center_config.go中ConfigCenterConfig这个结构体中, Namespace [filed](https://github.com/apache/dubbo-go/blob/master/config/config_center_config.go) 所对应的解析都是 namespace,而不是namespaceId，所以进行修改

**Comment by mosandao** [comment]
> > > > Some older versions user have already used the namespaceId as the key of the configuration. This change will cause incompatibility.
> > > 
> > > 
> > > Could you explain why do you change to namesapce? @mosandao
> > 
> > 
> > 因为在加载配置文件的时候，加载进来的key是namesapce，而不是namesapceId，导致无法从指定命名空间读取配置文件
> 
> 这个key在配置文件里面可以自己修改的。 @mosandao

感谢您的指导，改那个key以后可以注册进去了
那个配置中心，我需要关闭这个pr再重新提交新的pr么

**Comment by lzp0412** [comment]
> 心，我需要关闭这个pr再重新提交新的pr么

这个不需要改吧，上面set的是dubbo-go自身的配置，跟nacos配置没关系

**Pull request closed without merging**
