### PR TITLE
support multi address

### PR DESCRIPTION
**Pull request by xfstart07**
**What this PR does**:

支持多地址

### CODE REVIEW

**Review by zhaoyunxing92 — COMMENTED** [review]
这个有使用场景吗

**Comment by xfstart07** [comment]
> 

centerconfig (https://github.com/apache/dubbo-go-samples/blob/master/configcenter/zookeeper/go-server/conf/dubbogo.yml#L2) 配置多个就会报错

**Review by AlexStocks — APPROVED** [review]

**Comment by justxuewei** [comment]
> > 
> 
> centerconfig (https://github.com/apache/dubbo-go-samples/blob/master/configcenter/zookeeper/go-server/conf/dubbogo.yml#L2) 配置多个就会报错

什么是“配置多个就会报错”？能麻烦给个例子吗？

**Comment by LaurenceLiZhixin** [comment]
> > 
> 
> centerconfig (https://github.com/apache/dubbo-go-samples/blob/master/configcenter/zookeeper/go-server/conf/dubbogo.yml#L2) 配置多个就会报错

这个是3.0 的sample，为啥会改到1.5 的代码上？

**Review by zhaoyunxing92 — APPROVED** [review]

**Review by cjphaha — APPROVED** [review]

**Review by Mulavar — APPROVED** [review]

**Pull request merged**
