### PR TITLE
refactor: split metrics module into multiple files

### PR DESCRIPTION
**Pull request by ev1lQuark**
I have read the code related to the metrics module and plan to refactor the existing code before adding new metric instrumentation. This will make it easier for future development work. Could you please review the current file structure design to see if it conforms to community standards?

我阅读了 metrics 模块相关的代码，在添加新的指标埋点之前，先对已有的代码进行重构，便于后续的开发工作。请查看目前的文件结构设计是否符合社区规范？

### CODE REVIEW

**Comment by ev1lQuark** [comment]
What happend in CI? How should I modify it? @FinalT @justxuewei

**Comment by justxuewei** [comment]
> What happend in CI? How should I modify it? @FinalT @justxuewei

I rerun those CI tests.

**Comment by ev1lQuark** [comment]
> > What happend in CI? How should I modify it? @FinalT @justxuewei
> 
> I reran those CI tests.

Thank you. But it still went wrong.

```
2023-05-05T06:26:35.213Z	ERROR	polaris/service_discovery.go:193	Could not query the instances for service: myApp . It happened err Polaris-1004(ErrCodeAPITimeoutError): retry times exceed 1 in SyncGetResources, serviceKey: {namespace: "dubbogo", service: "myApp"}, timeout is 1s
dubbo.apache.org/dubbo-go/v3/registry/polaris.(*polarisServiceDiscovery).GetInstances
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/polaris/service_discovery.go:193
dubbo.apache.org/dubbo-go/v3/registry/servicediscovery.(*ServiceDiscoveryRegistry).LoadSubscribeInstances
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/servicediscovery/service_discovery_registry.go:256
dubbo.apache.org/dubbo-go/v3/registry/directory.NewRegistryDirectory
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/directory/directory.go:97
dubbo.apache.org/dubbo-go/v3/common/extension.GetDefaultRegistryDirectory
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/common/extension/registry_directory.go:40
dubbo.apache.org/dubbo-go/v3/registry/protocol.(*registryProtocol).Refer
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/protocol/protocol.go:152
dubbo.apache.org/dubbo-go/v3/config.(*ReferenceConfig).Refer
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/config/reference_config.go:238
dubbo.apache.org/dubbo-go/v3/config.(*ConsumerConfig).Load
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/config/consumer_config.go:132
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start.func1
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/config/root_config.go:212
sync.(*Once).doSlow
	/opt/hostedtoolcache/go/1.17.13/x64/src/sync/once.go:68
sync.(*Once).Do
	/opt/hostedtoolcache/go/1.17.13/x64/src/sync/once.go:59
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/config/root_config.go:210
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Init
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/config/root_config.go:205
dubbo.apache.org/dubbo-go/v3/config.Load
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/config/config_loader.go:59
github.com/apache/dubbo-go-samples/integrate_test/polaris/registry/tests/integration.TestMain
	/home/runner/work/dubbo-go/dubbo-go/samples/integrate_test/polaris/registry/tests/integration/main_test.go:60
main.main
	_testmain.go:45
runtime.main
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12a8695]

goroutine 84 [running]:
dubbo.apache.org/dubbo-go/v3/metadata/mapping/metadata.(*MetadataServiceNameMapping).Get(0x30, 0x30, {0x1eda438, 0xc0008c9740})
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/metadata/mapping/metadata/service_name_mapping.go:83 +0x75
dubbo.apache.org/dubbo-go/v3/registry/servicediscovery.(*ServiceDiscoveryRegistry).findMappedServices(0xc000295d40, 0xc0007fa000, {0x1eda438, 0xc0008c9740})
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/servicediscovery/service_discovery_registry.go:343 +0x5f
dubbo.apache.org/dubbo-go/v3/registry/servicediscovery.(*ServiceDiscoveryRegistry).getServices(0xc000295d40, 0xc00061beb8, {0x1eda438, 0xc0008c9740})
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/servicediscovery/service_discovery_registry.go:334 +0xc5
dubbo.apache.org/dubbo-go/v3/registry/servicediscovery.(*ServiceDiscoveryRegistry).Subscribe(0xc000295d40, 0xc0007fa000, {0x1eda2f8, 0xc0007fa780})
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/servicediscovery/service_discovery_registry.go:210 +0x250
dubbo.apache.org/dubbo-go/v3/registry/directory.(*RegistryDirectory).Subscribe(0xc0007fa780, 0xc0007fa000)
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/directory/directory.go:107 +0xbe
created by dubbo.apache.org/dubbo-go/v3/registry/protocol.(*registryProtocol).Refer
	/home/runner/go/pkg/mod/github.com/ev1l!quark/dubbo-go/v3@v3.0.0-20230427052823-322a9cdbded9/registry/protocol/protocol.go:164 +0x21d
FAIL	github.com/apache/dubbo-go-samples/integrate_test/polaris/registry/tests/integration	4.553s
FAIL
```

**Comment by jasondeng1997** [comment]
有设计文档吗

**Comment by chickenlj** [comment]
> 

https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/

https://cn.dubbo.apache.org/zh-cn/overview/core-features/observability/#metrics

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
