### PR TITLE
fix hash function bug

### PR DESCRIPTION
**Pull request by tangweihua163**
**What this PR does**:

fix bug

**Which issue(s) this PR fixes**:

Fixes #

`hash` function shifts a byte by 24/16/8 bits, always get zero.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by AlexStocks** [comment]
why do u change the first charactor of word to its low case?

**Comment by tangweihua163** [comment]
> why do u change the first charactor of word to its low case?

like all other three implements of `LoadBalance` interface, `least_active`, `round_robin` and `random`, `consistent_hash` should not export its detail out. this change is not necessary, but reasonable.

the focal point is the bug in `hash` method of type `consistentHashSelector`, left shifting a byte by more than 8 bits always got zero.

**Comment by AlexStocks** [comment]
I have changed the target branch from master to 3.0.

**Review by AlexStocks — APPROVED** [review]

**Review by LaurenceLiZhixin — APPROVED** [review]

**Review by zhaoyunxing92 — APPROVED** [review]
approved these changes

**Review by williamfeng323 — APPROVED** [review]

**Pull request merged**
