### PR TITLE
chores: replace deprecation ioutil functions

### PR DESCRIPTION
**Pull request by dongjiang1989**
Go 1.16 deprecated several io/ioutil functions.

`ioutil.ReadFile` -> `os.ReadFile`
`ioutil.ReadAll` -> `io.ReadAll`
`ioutil.ReadDir` -> `os.ReadDir`

ref: [https://pkg.go.dev/io/ioutil](https://pkg.go.dev/io/ioutil)

### CODE REVIEW

**Comment by justxuewei** [comment]
Hi @dongjiang1989. Lgtm! Could you backport this PR to `release-3.1`?

**Review by justxuewei — CHANGES_REQUESTED** [review]
Blocked temporarily

**Comment by dongjiang1989** [comment]
> Hi @dongjiang1989. Lgtm! Could you backport this patch to `release-3.1`?

cherry pick to release-3.1. 
#2597

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Comment by dongjiang1989** [comment]
> Lgtm, thanks!

Thanks. Please remove backport-needed label?🤔️

**Comment by justxuewei** [comment]
It is no needs to remove it.

**Pull request merged**
