### PR TITLE
Bugfix: nil attachments

### PR DESCRIPTION
**Pull request by rockXiaofeng**
**What this PR does**:
 Give it an initial value when attachments is nil
**Which issue(s) this PR fixes**:

Fixes https://github.com/apache/dubbo-go/issues/993

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by AlexStocks** [comment]
@pantianying @fangyincheng pls check this pr.

**Comment by pantianying** [comment]
I don't think this is a bug of dubbo-go. If there is no upstream attachment, why initialize one? But I also see no problem with your PR code if it improves protocol compatibility. However, we need to confirm the compatibility with the Java side

**Review by pantianying — COMMENTED** [review]
I don't think this is a bug of dubbo-go. If there is no upstream attachment, why initialize one? But I also see no problem with your PR code if it improves protocol compatibility. However, we need to confirm the compatibility with the Java side

**Comment by rockXiaofeng** [comment]
> I don't think this is a bug of dubbo-go. If there is no upstream attachment, why initialize one? But I also see no problem with your PR code if it improves protocol compatibility. However, we need to confirm the compatibility with the Java side

OK, I agree with you, but according to the issuer:
```
"Anything else we need to know?:
The same thing doesn't happen with the tengine's Java example. It works as the document states."
```
So, it should be confirmed whether java-server is compatible with this situation.

**Comment by rockXiaofeng** [comment]
I encountered this problem when I used the dubbo plugin of apisix as proxy, and dubbo-go as server provider,  so I submitted this PR and the problem was solved in my side.

**Comment by rockXiaofeng** [comment]
FYI (from com.alibaba/dubbo) : 
```
public class DecodeableRpcInvocation extends RpcInvocation implements Codec, Decodeable {
...
@Override
    public Object decode(Channel channel, InputStream input) throws IOException {
        ObjectInput in = CodecSupport.getSerialization(channel.getUrl(), serializationType)
                .deserialize(channel.getUrl(), input);
 
        String dubboVersion = in.readUTF();
        request.setVersion(dubboVersion);
        setAttachment(Constants.DUBBO_VERSION_KEY, dubboVersion);
 
        setAttachment(Constants.PATH_KEY, in.readUTF());
        setAttachment(Constants.VERSION_KEY, in.readUTF());
 ...
  Map<string, string=""> map = (Map<string, string="">) in.readObject(Map.class);
            if (map != null && map.size() > 0) {
                Map<string, string=""> attachment = getAttachments();
                if (attachment == null) {
                    attachment = new HashMap<string, string="">();
                }
                attachment.putAll(map);
                setAttachments(attachment);
            }
            //decode argument ,may be callback
            for (int i = 0; i < args.length; i++) {
                args[i] = decodeInvocationArgument(channel, this, pts, i, args[i]);
            }
 
            setArguments(args);
 
```

**Review by AlexStocks — APPROVED** [review]

**Review by fangyincheng — APPROVED** [review]

**Review by cityiron — APPROVED** [review]

**Pull request merged**
