### PR TITLE
added architecture files

### PR DESCRIPTION
**Pull request by Isaac-Zhang**
**What this PR does**:
added architecture files: png & pptx

### CODE REVIEW

**Comment by zouyx** [comment]
image

 I think the first space should similart to the second space.

@AlexStocks @hxmhlt @fangyincheng 

Should the pptx file move to another project, like https://github.com/dubbogo/resources ?

**Comment by Isaac-Zhang** [comment]
> 1. I think the first space should same to the second space.
> 
> image
> 
> 1. Should more space like provider block.
> 
> image
> 
> 1. Spacing to parent should be consistent, **Config center** should be aligned.
> 
> image
> 
> @AlexStocks @hxmhlt @fangyincheng
> 
> Should the pptx file move to another project, like https://github.com/dubbogo/resources ?

1&2&3 Done.

**Comment by Isaac-Zhang** [comment]
removed the source file of pptx.

**Comment by AlexStocks** [comment]
LGTM

**Pull request merged**
