### PR TITLE
feat: use notifyAll insteadOf notify for listener events notify

### PR DESCRIPTION
**Pull request by thehackercat**
Signed-off-by: xiaoxu <lexuscyborg103@gmail.com>

**What this PR does**: 
image

`Notify one after one` might have performance issues, this PR makes serviceListeners notify events concurrently and do not wait for notification complated.

I am wondering if it's needed to add a sync.WaitGroup after NotifyAll to wait notification completed or not.

**Which issue(s) this PR fixes**: 
Fixes https://github.com/apache/dubbo-go/issues/2030

**You should pay attention to items below to ensure your pr passes our ci test**
We do not merge pr with ci tests failed

- [x] All ut passed (run 'go test ./...' in project root)
- [x] After go-fmt ed , run 'go fmt project' using goland.
- [x] Golangci-lint passed, run 'sudo golangci-lint run' in project root.
- [x] After import formatted, (using [imports-formatter](https://github.com/dubbogo/tools#5-how-to-get-imports-formatter) to run 'imports-formatter .' in project root, to format your import blocks, mentioned in [CONTRIBUTING.md](https://github.com/apache/dubbo-go/blob/master/CONTRIBUTING.md) above) 
- [ ] Your new-created file needs to have [apache license](https://raw.githubusercontent.com/dubbogo/resources/master/tools/license/license.txt) at the top, like other existed file does.
- [ ] All integration test passed. You can run integration test locally (with docker env). Clone our [dubbo-go-samples](https://github.com/apache/dubbo-go-samples) project and replace the go.mod to your dubbo-go, and run 'sudo sh start_integration_test.sh' at root of samples project root. (M1 Slice is not Support)

### CODE REVIEW

**Comment by thehackercat** [comment]
@chickenlj PTAL~

**Comment by chickenlj** [comment]
Please take a look at the build and test failures.

**Comment by thehackercat** [comment]
> Please take a look at the build and test failures.

@chickenlj Hi I've passed `make test` , `go fmt` and `import-formatted` locally, it seems the ci failure is not introduced by this PR.

image
image

Do you have any idea how to fix that?

**Comment by justxuewei** [comment]
> Do you have any idea how to fix this?

IMO, please try to checkout 3.0 branch and pull the latest commits, then rebase the 3.0 branch to `thehackercat:thehackercat-patch-2`.

**Comment by chickenlj** [comment]
Probably because there are failures on the 3.0 base branch. We need to fix failures there first.

**Comment by thehackercat** [comment]
golangci-lint passed after rebased this PR  https://github.com/apache/dubbo-go/pull/2047, will check the ut failure later

**Review by justxuewei — APPROVED** [review]

**Review by Lvnszn — APPROVED** [review]

**Pull request merged**
