### PR TITLE
Fix url attributes merge

### PR DESCRIPTION
**Pull request by FinalT**
fix pr #2503

### CODE REVIEW

**Review by chickenlj — APPROVED** [review]
LGTM.

**Review by chickenlj — CHANGES_REQUESTED** [review]
How about we make `MergeURL` a method of *URL?

Because currently, the behaviour or priority of attribute keys is not determined since it depends on the sequence of parameters - the first URL always gets high priority, but not all maintainers know about this rule, so if they don't correctly put these two URLs, the result is probably not what they expect.

**Comment by DMwangnima** [comment]
> How about we make `MergeURL` a method of *URL?
> 
> Because currently, the behaviour or priority of attribute keys is not determined since it depends on the sequence of parameters - the first URL always gets high priority, but not all maintainers know about this rule, so if they don't correctly put these two URLs, the result is probably not what they expect.

+1. We need to distinguish between baseURL and addURL.

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
