### PR TITLE
[WIP] remove black list module

### PR DESCRIPTION
**Pull request by Threadalive**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```1.5版本的黑名单机制中会将报错的服务端实例记录黑名单,即使服务恢复正常后,一段时间内调用仍会出现No provider is available because can't connect server.的错误,实际使用中不太合理.
```

### CODE REVIEW

**Review by zouyx — COMMENTED** [review]
why did you remove this module？

**Review by AlexStocks — APPROVED** [review]

**Comment by AlexStocks** [comment]
why  are there so many conflictions?

**Comment by LaurenceLiZhixin** [comment]
ping @Threadalive 
Any feedback?

**Comment by Threadalive** [comment]
> why did you remove this module？

This module causes when an exception occurs on the server side, the consumer will add the server ip to the blacklist, resulting in an error when calling the ip within a period of time: No provider is available because can't connect server. In fact, the server may just be Because some processing normally reports an error.

**Pull request closed without merging**
