### PR TITLE
provider can get attachment in ctx

### PR DESCRIPTION
**Pull request by pantianying**
**What this PR does**:

before this , consumer can send attachment from context
after this
Provider get attachment in context

### CODE REVIEW

**Comment by pantianying** [comment]
> attachment本质上是key-value，如果只是把attachment里面的key-value拉平塞进去context，而不是直接塞整个attachment，这样是否可行？

这里主要是参照java的模式 java中是通过context.getAttachment()获取到一个map[string]string ,而且客户端发送attachment之前已经确定格式了 现在也不好改了

**Comment by cvictory** [comment]
晚点合并，等 https://github.com/apache/dubbo-go/pull/495 合并完成之后，再在纸上修改吧。

**Comment by zouyx** [comment]
still failing. boss Pan

**Comment by pantianying** [comment]
> https://github.com/apache/dubbo-go/blob/c6be5541c6329de6bd731c56f93c69ed5ef383c0/common/proxy/proxy_factory/default.go#L89
> 
> 
> This line of code should be modified, otherwise modified attachment will not be returned.

现在暂不考虑服务端修改的ctx返回，因为ctx的传值机制是新生成ctx对象，只能向下传递，暂时无法向上传递修改内容

**Pull request merged**
