### PR TITLE
fixed invalid timeout config setting

### PR DESCRIPTION
**Pull request by yxcodebase**

### CODE REVIEW

**Review by zouyx — COMMENTED** [review]
why do you disable this code?

**Comment by AlexStocks** [comment]
@yxcodebase pls tell us why u remark "os.Exit(0)"?

**Comment by yxcodebase** [comment]
Exit immediately regardless of whether the timeout is set。

**Comment by cityiron** [comment]
Do not understand, can talk in detail, are you in the group of dingding 31363295

**Pull request closed without merging**
