### PR TITLE
Fix: change service_name like java style on nacos

### LINKED ISSUE #1331: Nacos 注册的group和version未和java侧对齐
**What happened**:
dubbo 3.0 +  dubbogo 3.0
java侧注册key为`interfaceName:group:version` 当group和version为空时注册`interfaceName::`
go侧当group和version为空时订阅`interfaceName`
导致go侧服务发现失败
考虑该情景是否在1.5、3.0、其他注册中心、go作为server端时存在问题。

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by ChangedenCZD**
fixed: #1331

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #1331

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by LaurenceLiZhixin** [comment]
Pls Change your target branch to 1.5/3.0

**Comment by ChangedenCZD** [comment]
@LaurenceLiZhixin 已切换至3.0

**Review by AlexStocks — APPROVED** [review]

**Comment by AlexStocks** [comment]
Pls change the pr title. We will list ur pr when we publish a new dubbogo version. This title is so confusing.

**Comment by ChangedenCZD** [comment]
> Pls change the pr title. We will list ur pr when we publish a new dubbogo version. This title is so confusing.

done

**Pull request closed without merging**
